apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-demo
  name: np-app-demo
spec:
  ports:
  - port: 9004
    protocol: TCP
    targetPort: 9004
    nodePort: 30007
  selector:
    app: app-demo
  type: NodePort
